wip
equinor/dm-cli pull request #74
Opened 2023-03-21 15:07 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change

2023-03-22 13:24 UTC, KristianKjerstad commented
see question posted in https://github.com/equinor/dm-cli/issues/70:
 
 should we use the exception wrapper function if API errors are accepted?

2023-03-23 06:49 UTC, soofstad requested changes

2023-03-23 06:49 UTC, soofstad commented on dm_cli/bin/dm
Think we should wrap line 259 and 79 as well.
In fact, and think the file, and the whole codebase would be more maintanable if we exctract the code from each command into a separate "standard python function" in separate files.

So that the functions with the click decorators onlt extracts the arguments, and then passing them to a "backend function".
Then we would not need to do this "context.invoke()" thing ether.
Would then also need to pass the "dmss_api" object i supose.

2023-03-23 06:49 UTC, soofstad commented on dm_cli/bin/dm
More similar to a "use_case" pattern, with one common exception wrapper

2023-03-23 07:11 UTC, KristianKjerstad commented on dm_cli/bin/dm
will fix line 259 and 79!

Agree, would be better to introduce a pattern like that. It would also make it easier to create tests for each command.

This should probably be a new issue

2023-03-23 07:17 UTC, KristianKjerstad commented on dm_cli/bin/dm
#75

2023-03-23 08:53 UTC, soofstad approved these changes

2023-03-23 10:39 UTC, merged