_fix: add type to Dependency class
equinor/dm-cli pull request #87
Opened 2023-04-21 11:57 UTC by KristianKjerstad

## What does this pull request change?

## Why is this pull request needed?

## Issues related to this change

2023-04-21 13:53 UTC, KristianKjerstad commented
needs https://github.com/equinor/data-modelling-storage-service/pull/406

2023-04-24 11:10 UTC, soofstad requested changes

2023-04-24 11:10 UTC, soofstad commented on tests/test_data/test_app_dir_struct/data/DemoApplicationDataSource/instances/package.json
> +    "type": "dmss://system/SIMOS/Meta",
This change should not be needed.
If the alias does not work for "Meta", we should fix that.

2023-04-27 08:40 UTC, soofstad commented
No longer neede as of: https://github.com/equinor/dm-cli/pull/88

2023-04-27 08:40 UTC, closed without merging